### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by gitaaronc** [pmezydlo/SPI_slave_driver_implementation#3]
Hello,

Since updating to your latest code, I am unable to compile.
I receive the following errors.
/root/github/SPI_slave_driver_implementation/driver/spi-slave-dev.c:279:3: error: implicit declaration of function 'idr_pre_get' [-Werror=implicit-function-declaration]
   if (!idr_pre_get(&spislave_idr, GFP_KERNEL) == 0) {
   ^
/root/github/SPI_slave_driver_implementation/driver/spi-slave-dev.c:285:3: error: implicit declaration of function 'idr_get_new' [-Werror=implicit-function-declaration]
   ret = idr_get_new(&spislave_idr, data, &data_id);
   ^

I've tried kernel 4.4.9-bone10 and 4.4.9-ti-r25

Any thoughts?

Thanks.

**Comment by pmezydlo** [comment]
Hi, 

This project is now very developed by me. Significant changes are introduced and  on all does not work. Please wait 1-2 weeks for stabilization.

Thanks

**Comment by gitaaronc** [comment]
Last update fixed the compiling issue.
